import type { Metadata } from 'next'

import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

// export const metadata: Metadata = {
//   title: 'HiKing Traveler App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="We want to be on each of your journeys seeking the satisfaction of seeing the incorruptible beauty of nature in Sri Lanka."
          />
        <meta name='keywords' content='nike shoes premium'></meta>
        <link rel="apple-touch-icon" href="/logo.svg" />
        <title>Hiking Traveler App</title>

        <meta property="og:title" content="Hiking Traveler App by Vinojan"></meta>
        <meta property="og:description" content="We want to be on each of your journeys seeking the satisfaction of seeing the incorruptible beauty of nature in Sri Lanka."></meta>
        <meta property="og:type" content="website"/>
        <meta property="og:url" content="https://hiking-traveler-app.vercel.app/" />
        <meta property="og:image" content="https://github-production-user-asset-6210df.s3.amazonaws.com/48822560/276494558-229d517c-9535-4192-b5e3-c58fdb37905e.png"></meta>
        <meta property="og:site_name" content="Hiking Traveler App by Vinojan"></meta>
      </head>

      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
